### PR TITLE
add qBittorrent

### PR DESCRIPTION
**Pull request by arkaitzsilva**
qBittorrent icons including system tray icon

### CODE REVIEW

**Comment by arkaitzsilva** [comment]
On recent qbittorrent-tray.svg changes the qt letters are not centered

**Comment by UriHerrera** [comment]
> On recent qbittorrent-tray.svg changes the qt letters are not centered

image

The objects in the SVG can't be closer, otherwise, they will look bad, like one larger object that makes it indistinguishable from each other.

The objects, too, must be aligned to the pixel grid, so all icons are pixel perfect, otherwise, they will look blurry.

**Comment by arkaitzsilva** [comment]
Yes 16 pixel icon is perfect, I'm referring to 22 pixels one.
qbittorrent-tray

**Comment by UriHerrera** [comment]
Fixed.

**Pull request merged**
